language: c
sudo: false
compiler:
- clang
- gcc
cache:
  directories:
    - $HOME/.cache/pip
install:
- pip install --user autobahntestsuite
script:
- ./autogen.sh
- ./configure --enable-autobahntest=yes
- make distcheck
deploy:
  provider: releases
  api_key:
    secure: fVMvvlhsginfIB7gEhAoKG7xzvF6D94yl8Z+jjfHQG4YtG3SScKVeQUnpWK7NhT90uoUfPnxd5dN3ZWlApoLBSz7iVD0sT1+VGYerM0Gn3LTUj3xvTB3WAAft6YePKhQeJfduzSNqsRjQ7buKgI1SFH0Ek5xwZe4Kl/O/D2Tsw0=
  file:
    - nanomsg-${TRAVIS_TAG}.zip
    - nanomsg-${TRAVIS_TAG}.tar.gz
  skip_cleanup: true
  on:
    tags: true
    repo: nanomsg/nanomsg
